name: Deploy Site

on:
  push:
    branches: [ main ]
    paths:
      - 'site/**'
      - '.github/workflows/**'
      - 'terraform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AKIA4EXAMPLEID77Y }}
          aws-secret-access-key: ${{ 40irpeEXAMPLESECRETKEYgn4RB0nS }}
          aws-region: ${{ us-east-1 }}

      - name: Sync site to S3
        run: |
          aws s3 sync site/ s3://my-unique-bucket-name-1234 --acl public-read --delete

      - name: Print site URL
        run: echo "Site URL: http://my-unique-bucket-name-1234.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com"
